import os

FACEGREP_POSTGRES_URI = os.getenv("FACEGREP_POSTGRES_URI")
FACEGREP_NEO4J_URI = os.getenv("FACEGREP_NEO4J_URI")
FACEGREP_NEO4J_USERNAME = os.getenv("FACEGREP_NEO4J_USERNAME")
FACEGREP_NEO4J_PASSWORD = os.getenv("FACEGREP_NEO4J_PASSWORD")
FACEGREP_NEO4J_URI = os.getenv("FACEGREP_NEO4J_URI")
FACEGREP_IMAGE_TMPDIR = os.getenv("FACEGREP_IMAGE_TMPDIR")
FACEGREP_IMAGE_DIR = os.getenv("FACEGREP_IMAGE_DIR")
